name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main   # or 'master' if that's your default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: lost-473920
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to GCS
        run: |
          gsutil -m rsync -r ./ gs://www.berrycom.co.ke
